/**
 * THANE406 — no-element-id
 *
 * The compiler generates element IDs using the pattern `bN` (e.g. `b0`, `b1`).
 * User-authored `html` tagged template literals should not use IDs that match
 * this pattern, as they would collide with compiler-emitted anchors and cause
 * incorrect binding behaviour at runtime.
 *
 * All other user-defined IDs are allowed:
 *
 *   html`<div id="main">...</div>`          // ✅ allowed
 *   html`<table id="tbody">...</table>`      // ✅ allowed
 *   html`<button id="run">...</button>`      // ✅ allowed
 *
 *   html`<div id="b0">...</div>`             // ❌ THANE406 — conflicts with compiler
 *   html`<div id="b12">...</div>`            // ❌ THANE406 — conflicts with compiler
 *
 * Compiler-emitted anchors like `<template id="b0">` are injected after
 * linting, so this rule produces no false positives.
 */

import ts from 'typescript';
import type { Diagnostic } from '../../../types.js';
import type { LintRuleDefinition } from './types.js';
import { ErrorCode, createWarning } from '../../../errors.js';
import { FN } from '../../../utils/constants.js';

/**
 * Regex matching `id="..."` or `id='...'` attributes in HTML.
 * Captures the ID value for pattern checking.
 */
const ID_ATTR_RE = /\bid\s*=\s*(?:"([^"]*)"|'([^']*)')/g;

/**
 * Compiler-reserved ID pattern: `b` followed by one or more digits.
 * These are generated by the CTFE counter and binding compiler.
 */
const RESERVED_ID_RE = /^b\d+$/;

const isHtmlTag = (node: ts.TaggedTemplateExpression): boolean => {
  const tag = node.tag;
  return ts.isIdentifier(tag) && tag.text === FN.HTML;
};

/**
 * Given a position inside a template literal's text, compute the 1-based
 * line and column in the original source file.
 */
const resolvePosition = (
  sourceFile: ts.SourceFile,
  templateStart: number,
  offsetInTemplate: number,
): { line: number; column: number } => {
  const { line, character } = sourceFile.getLineAndCharacterOfPosition(
    templateStart + offsetInTemplate,
  );
  return { line: line + 1, column: character + 1 };
};

/**
 * Scan a single template span text for `id="..."` / `id='...'` occurrences.
 * Only flags IDs that match the compiler-reserved pattern (b0, b1, ...).
 */
const scanText = (
  text: string,
  textStartInFile: number,
  sourceFile: ts.SourceFile,
  filePath: string,
  diagnostics: Diagnostic[],
): void => {
  ID_ATTR_RE.lastIndex = 0;
  let match: RegExpExecArray | null;
  while ((match = ID_ATTR_RE.exec(text)) !== null) {
    const idValue = match[1] ?? match[2] ?? '';
    if (!RESERVED_ID_RE.test(idValue)) continue; // allow non-reserved IDs
    const { line, column } = resolvePosition(sourceFile, textStartInFile, match.index);
    diagnostics.push(
      createWarning(
        `Element ID "${idValue}" may conflict with compiler-reserved IDs (pattern: b0, b1, ...). ` +
        'Consider using a different ID to avoid binding collisions.',
        { file: filePath, line, column },
        ErrorCode.NO_ELEMENT_ID,
      ),
    );
  }
};

const check = (sourceFile: ts.SourceFile, filePath: string): Diagnostic[] => {
  const diagnostics: Diagnostic[] = [];

  const visit = (node: ts.Node) => {
    if (ts.isTaggedTemplateExpression(node) && isHtmlTag(node)) {
      const template = node.template;

      if (ts.isNoSubstitutionTemplateLiteral(template)) {
        scanText(template.text, template.getStart() + 1, sourceFile, filePath, diagnostics);
      } else if (ts.isTemplateExpression(template)) {
        scanText(
          template.head.text,
          template.head.getStart() + 1,
          sourceFile,
          filePath,
          diagnostics,
        );

        for (const span of template.templateSpans) {
          scanText(
            span.literal.text,
            span.literal.getStart() + 1,
            sourceFile,
            filePath,
            diagnostics,
          );
        }
      }
    }

    ts.forEachChild(node, visit);
  };

  visit(sourceFile);
  return diagnostics;
};

export const noElementId: LintRuleDefinition = {
  meta: {
    code: ErrorCode.NO_ELEMENT_ID,
    name: 'no-element-id',
    severity: 'warning',
    description:
      'Element IDs matching compiler-reserved patterns (b0, b1, ...) may collide with compiler-generated anchors.',
  },
  check,
};
