import { RUNTIME_HELPER } from '../runtime/internal-helpers.js';

export const COMPILER_BIND_FN = {
  TEXT: '__bindText',
  STYLE: '__bindStyle',
  ATTR: '__bindAttr',
  IF: RUNTIME_HELPER.IF,
  IF_EXPR: RUNTIME_HELPER.IF_EXPR,
  KEYED_RECONCILER: RUNTIME_HELPER.KEYED_RECONCILER,
  ENABLE_STYLES: RUNTIME_HELPER.ENABLE_STYLES,
  REGISTER_COMPONENT: RUNTIME_HELPER.REGISTER_COMPONENT,
  REGISTER_COMPONENT_LEAN: RUNTIME_HELPER.REGISTER_COMPONENT_LEAN,
  DESTROY_CHILD: RUNTIME_HELPER.DESTROY_CHILD,
} as const;
